language: scala
scala:
- 2.11.6
script:
- sbt clean "project powerspy-core" coverage test
after_success:
- sbt "project powerspy-core" coverageReport
- sbt "project powerspy-core" codacyCoverage
- sbt "project powerspy-core" coveralls
