language: scala

scala:
  - 2.12.4

jdk:
  - oraclejdk8

addons:
  hostname: localhost

script:
  - sbt clean compile "project core" coverage test

after_success:
  - sbt "project core" coverageReport
  - sbt "project core" coveralls
